name: Build JAR
on: 
  push:
  pull_request:
    branches: 
      -master
      -GreihMurray-patch-1
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Change wrapper permissions
      run: chmod +x micronautpi4j-utils/gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: micronautpi4j-utils/
    - name: Execute Gradle build
      run: ./gradlew shadowJar
    - name: Upload built JAR
      uses: actions/upload-artifact@v3
      with:
        path: micronautpi4j-utils/build/libs
