.micronaut:
  application:
    name: components

pi4j:
  # tag::spi[]
  spi:
    rfid:                   # <1>
      name: MFRC522         # <2>
      address: 8            # <3>
      baud: 500000          # <4>
      reset-pin: 25         # <5>
  # end::spi[]

  # tag::pwm[]
  pwm:
    active-buzzer:               # <1>
      name: active-buzzer        # <2>
      address: 17                # <3>
      pwmType: SOFTWARE          # <4>
      provider: pigpio-pwm       # <5>
      initial: 0                 # <6>
      shutdown: 0                # <7>
    passive-buzzer:
      name: passive-buzzer
      address: 17
      pwmType: SOFTWARE
      provider: pigpio-pwm
      initial: 0
      shutdown: 0
    servo-motor:
      name: Servo Motor
      address: 17
      pwmType: SOFTWARE
      provider: pigpio-pwm
      initial: 0
      shutdown: 0
    motor:
      name: Motor
      address: 18
      pwmType: SOFTWARE
      provider: pigpio-pwm
      initial: 0
      shutdown: 0
    fan:
      name: FAN
      address: 18
      pwm-type: SOFTWARE
      provider: pigpio-pwm
      initial: 0
      shutdown: 0
  # end::pwm[]

  # tag::i2c[]
  i2c:
    lcd:                                  # <1>
      name: lcd                           # <2>
      bus: 1                              # <3>
      device: 0x27                        # <4>
    4digit7segment:
      name: 4 Digit 7 Segment Display
      bus: 1
      device: 0x3F
      segments:
        segmentA:
          pin: 18
          state: "LOW"
        segmentB:
          pin: 22
          state: "LOW"
        segmentC:
          pin: 24
          state: "LOW"
        segmentD:
          pin: 26
          state: "LOW"
        segmentE:
          pin: 28
          state: "LOW"
        segmentF:
          pin: 32
          state: "LOW"
        segmentG:
          pin: 36
          state: "LOW"
        decimal-point:
          pin: 38
          state: "LOW"
        digits:
          digit0:
            pin: 11
            state: "LOW"
          digit1:
            pin: 13
            state: "LOW"
          digit2:
            pin: 15
            state: "LOW"
          digit3:
            pin: 17
            state: "LOW"
  # end::i2c[]

  # tag::digitalInput[]
  digital-input:
    photo-resistor-input:                 # <.>
      name: Photo Resistor Input          # <.>
      address: 4                          # <.>
      debounce: 100000                    # <.>
      pull: PULL_DOWN                     # <.>
      provider: pigpio-digital-input      # <.>
    button-input-1:
      name: Push Button Input
      address: 16
      pull: PULL_DOWN
      debounce: 30
      provider: pigpio-digital-input
    button-input-2:
      name: Push Button Input
      address: 21
      pull: PULL_DOWN
      debounce: 30
      provider: pigpio-digital-input
    button-input-3:
      name: Push Button Input
      address: 18
      pull: PULL_DOWN
      debounce: 30
      provider: pigpio-digital-input
    slide-switch-input:
      name: Slide Switch Input
      address: 18
      pull: PULL_DOWN
      debounce: 3000
      provider: pigpio-digital-input
    slide-switch-input-2:
      name: Slide Switch Input
      address: 22
      pull: PULL_DOWN
      debounce: 3000
      provider: pigpio-digital-input
    touch-switch-input:
      name: Touch Switch Input
      address: 17
      pull: PULL_DOWN
      debounce: 200000
      provider: pigpio-digital-input
    micro-switch:
      name: Micro Switch
      address: 19
      pull: PULL_DOWN
      debounce: 200000
      provider: pigpio-digital-input
    pir-sensor:
      name: PIR Sensor
      address: 13
      pull: PULL_DOWN
      debounce: 30000
      provider: pigpio-digital-input
    ultra-sonic-echo:
      name: UltraSonic Sensor Input
      address: 24
      pull: PULL_DOWN
      debounce: 3000
      provider: pigpio-digital-input
    tilt-switch-input:
      name: Tilt Switch Input
      address: 17
      pull: PULL_DOWN
      debounce: 5000
      provider: pigpio-digital-input
    speed-sensor:
      name: Speed Sensor           # <1>
      address: 17                 # <2>
      pulses-per-revolution: 20    # <3>
      provider: pigpio-digital-input # <4>
      debounce: 500                # <5>
  # end::digitalInput[]

  # tag::digitalOutput[]
  digital-output:
    led:                                    # <1>
      name: LED Output                      # <2>
      address: 17                           # <3>
      shutdown: LOW                        # <4>
      initial: LOW                         # <5>
      provider: pigpio-digital-output       # <6>
    led2:
      name: LED Output
      address: 26
      shutdown: HIGH
      initial: HIGH
      provider: pigpio-digital-output
    photo-resistor-output:
      name: Photo Resistor Output
      address: 27
      shutdown: LOW
      initial: HIGH
      provider: pigpio-digital-output
    ultra-sonic-trig:
      name: UltraSonic Sensor Output
      address: 23
      shutdown: LOW
      initial: LOW
      provider: pigpio-digital-output
  # end::digitalOutput[]

  # tag::multiInput[]
  multi-digital-input:                     # <.>
    rotary-encoder:                        # <.>
      name: Rotary Encoder                 # <.>
      addresses: 27,18,17                  # <.>
      debounces: 6000,500,500              # <.>
      pulls: PULL_DOWN,PULL_UP,PULL_UP     # <.>
      shutdown: LOW                        # <.>
      initial: HIGH                        # <.>
      provider: pigpio-digital-input       # <.>
    rotary-encoder-2:
      name: Rotary Encoder 2
      addresses: 12, 16, 20
      debounces: 6000, 500, 500
      pulls: PULL_DOWN, PULL_UP, PULL_UP
      shutdown: LOW
      initial: HIGH
      provider: pigpio-digital-input
  # end::multiInput[]

  # tag::multiPWM[]
  multi-pwm:
    rgb-led:                                    # <.>
      name: RGB LED                             # <.>
      addresses: 17, 18, 27                     # <.>
      pwmTypes: SOFTWARE, SOFTWARE, SOFTWARE    # <.>
      provider: pigpio-pwm                      # <.>
      initials: 0, 0, 0                         # <.>
      shutdowns: 0, 0, 0                        # <.>
    rgb-led-2:
      name: RGB LED 2
      addresses: 18, 27, 22
      pwmTypes: SOFTWARE, SOFTWARE, SOFTWARE
      provider: pigpio-pwm
      initials: 0, 0, 0
      shutdowns: 0, 0, 0
      #    4digit7segment:
      #      name: 4 Digit 7 Segment Display
      #      addresses: 18, 22, 24, 26, 28, 32, 36, 38, 11, 13, 15, 17 # A, B, C, D, E, F, G, DP, DIGIT1, DIGIT2, DIGIT3, DIGIT4
      #      shutdowns: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      #      initials: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      #      pwmTypes: SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE, SOFTWARE
      #      provider: pigpio-pwm
  # end::multiPWM[]

  # tag::multiOutput[]
  #      multi-digital-output:
  #        4digit7segment:
  #          name: 4 Digit 7 Segment Display
  #          addresses: 18, 22, 24, 26, 28, 32, 36, 38, 11, 13, 15, 17 # A, B, C, D, E, F, G, DP, DIGIT1, DIGIT2, DIGIT3, DIGIT4
  #          shutdowns: LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW
  #          initials: HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH
  #          provider: pigpio-digital-output
  # end::multiOutput[]
